from wand.image import Image
from PyPDF2 import PdfFileMerger, PdfFileReader
import os
import shutil
import glob

def get_file_name(path_to_file):
    '''
    Get the filename from path file
    '''
    return path_to_file.split('/')[-1]

def crop_source_files(_path):
    '''
    Get the pdf invoice from telpark, that must be downloaded into source folder
    and this function will parse all files with pdf extension.
    '''
    if not os.path.exists(tmp):
        os.makedirs(tmp)
    else:
        shutil.rmtree(tmp)
        os.makedirs(tmp)
    print "Cropping files..."
    for _file in glob.glob(_path):
        with Image(filename=_file, resolution=200) as img:
             img.compression_quality = 99
             img.crop(170, 100, width=1320, height=900)
             img.save(filename="./tmp/" + get_file_name(_file))

def concatenate_files(_path):
    '''
    Get all images generated by the crop function and concatenate 2 by 2 into
    1 file
    '''
    print "Concatenating files..."
    file_list = glob.glob(_path)
    for _file in range(0, len(file_list), 2):
        if file_list.index(file_list[_file]) != len(file_list) - 1:
            file1 = file_list[_file]
            file2 = file_list[_file + 1]
            print "\t {} + {}".format(get_file_name(file1),get_file_name(file2))
            with Image() as blankimage:
                with Image(filename=file1, resolution=200) as img1:
                    w = img1.width; h = img1.height
                    with Image(filename=file2, resolution=200) as img2:
                        blankimage.blank(w, h*2)
                        blankimage.composite(img1, 0, 0)
                        blankimage.composite(img2, 0, h)
                        blankimage.save(filename=file1)
            os.remove(file2)
        else:
            file1 = file_list[_file]
            with Image() as blankimage:
                with Image(filename=file1, resolution=200) as img1:
                    w = img1.width; h = img1.height
                    blankimage.blank(w, h*2)
                    blankimage.composite(img1, 0, 0)
                    blankimage.save(filename=file1)

        os.rename(file1, "./tmp/new_mix_" + str(_file) + ".tmp")

def merge_pdfs(_path):
    '''
    Merge pdf files from tmp folder and write into destination one
    '''
    print "Creating release pdf..."
    file_list = glob.glob(_path)
    merger = PdfFileMerger()
    for filename in file_list:
        merger.append(PdfFileReader(file(filename, 'rb')))

    merger.write(final_file)

def trash_cleaner(_path):
    '''
    Erase tmp folder
    '''
    shutil.rmtree(_path)

## Variables
tmp = './tmp/'
source = './source/'
destination = './dest/'
final_file = "final.pdf"

## Main
crop_source_files(source + '*.pdf')
concatenate_files(tmp + '*.pdf')
merge_pdfs(tmp + '*.tmp')
trash_cleaner(tmp)
